require "plugins"

require "settings/functions"
require "settings/options"
require "settings/keymaps"

require "plugins/configs/gruvbox"
require "plugins/configs/alpha"
require "plugins/configs/buffjump"
require "plugins/configs/cmp"
require "plugins/configs/diffview"
require "plugins/configs/lightline"
require "plugins/configs/mason"
require "plugins/configs/lspconfig"
require "plugins/configs/persistence"
require "plugins/configs/neo-tree"
require "plugins/configs/null-ls"
require "plugins/configs/nvim-surround"
require "plugins/configs/telescope"
require "plugins/configs/vim-test"
